/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xYHqD5MkVkT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function NavBar() {
  return (
    <nav className="fixed inset-x-0 top-0 z-50 bg-white shadow-sm dark:bg-gray-950/90">
      <div className="w-full max-w-7xl mx-auto px-4">
        <div className="flex justify-between h-14 items-center">
          <Link href="#" className="flex items-center" prefetch={false}>
            <p className="font-semibold">SpookyScary</p>
            <span className="sr-only">SpookyScary</span>
          </Link>
          <nav className="hidden md:flex gap-4">
           
          </nav>
          <div className="flex items-center gap-4">
            <Link href="/jatek">
              <Button size="sm">Játék</Button>
            </Link>
          </div>
        </div>
      </div>
    </nav>
  )
}
